CONVERT_TO = rp2040_ce
SPLIT_KEYBOARD = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes

# BACKLIGHT_ENABLE = no
# BACKLIGHT_ENABLE = yes
# RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = yes

EXTRAKEY_ENABLE = yes
ENCODER_MAP_ENABLE = yes
LTO_ENABLE = yes

NKRO_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_DRIVER_ENABLE = yes
WPM_ENABLE = yes
# TAP_DANCE_ENABLE = no


COMMAND_ENABLE = no
CONSOLE_ENABLE = no
# MOUSEKEY_ENABLE = no
COMBO_ENABLE = no
